import {t,es,esc,api,download} from './common.js';
export async function renderAnalytics(root){
 root.innerHTML=`<div class="pagehead"><h1>${t('Visitor analytics','Estadísticas de visitas')}</h1><p>${t('Measured page views and optional repeat-visitor estimates. Collection starts with this release; historical traffic is unavailable.','Cargas de páginas medidas y estimaciones opcionales de visitas repetidas. La recopilación comienza con esta versión; no hay historial anterior.')}</p></div><div class="toolbar"><label for="analytics-days">${t('Reporting period · UTC days','Período · días UTC')}</label><select id="analytics-days"><option value="1">${t('Today','Hoy')}</option><option value="7" selected>${t('Last 7 days','Últimos 7 días')}</option><option value="30">${t('Last 30 days','Últimos 30 días')}</option></select><button class="btn" id="analytics-refresh">${t('Refresh','Actualizar')}</button><button class="btn" id="analytics-export" disabled>${t('Export aggregate report','Exportar informe agregado')}</button></div><p id="analytics-status" role="status"></p><div id="analytics-report"></div>`;
 let report=null,serial=0;
 const table=(title,items)=>`<article class="card"><h2>${title}</h2>${items.length?`<div class="table-wrap"><table><thead><tr><th>${t('Category','Categoría')}</th><th>${t('Page views','Páginas vistas')}</th></tr></thead><tbody>${items.map(x=>`<tr><td>${esc(x.label)}</td><td>${x.views}</td></tr>`).join('')}</tbody></table></div>`:`<p>${t('No measurements yet.','Aún no hay mediciones.')}</p>`}</article>`;
 async function load(){const n=++serial;report=null;document.querySelector('#analytics-export').disabled=true;document.querySelector('#analytics-status').textContent=t('Loading…','Cargando…');try{const r=await api('/api/analytics?days='+document.querySelector('#analytics-days').value);if(n!==serial)return;report=r;const dayIps=r.daily.reduce((sum,d)=>sum+d.ips,0),metrics=[[r.totals.views,t('Page views','Páginas vistas')],[r.totals.browsers,t('Distinct opted-in browsers','Navegadores distintos con permiso')],[dayIps,t('Daily unique IP estimates, summed','Suma de IP distintas diarias estimadas')],[r.totals.consentedViews,t('Views with optional consent','Vistas con permiso opcional')]];
 document.querySelector('#analytics-report').innerHTML=`<div class="metrics">${metrics.map(([n,label])=>`<div class="metric"><strong>${n}</strong>${label}</div>`).join('')}</div><div class="notice">${t('These are not counts of people or physical devices. The same IP on two days counts twice in the daily sum. Optional counts cover only consenting browsers; private browsing, shared Wi-Fi, VPNs and hosting proxies affect estimates.','No son conteos de personas ni dispositivos físicos. La misma IP en dos días cuenta dos veces en la suma. Los conteos opcionales solo incluyen navegadores con permiso; la navegación privada, Wi-Fi compartido, VPN y proxies afectan las estimaciones.')} ${r.totals.ipViews} ${t('views had a usable hosting IP signal.','vistas tuvieron una señal IP utilizable del alojamiento.')}</div><article class="card"><h2>${t('Daily traffic','Tráfico diario')}</h2>${r.daily.length?`<div class="table-wrap"><table><thead><tr><th>${t('Date (UTC)','Fecha (UTC)')}</th><th>${t('Views','Vistas')}</th><th>${t('Opted-in browsers','Navegadores con permiso')}</th><th>${t('Estimated IPs','IP estimadas')}</th></tr></thead><tbody>${r.daily.map(d=>`<tr><td>${d.day}</td><td>${d.views}</td><td>${d.browsers}</td><td>${d.ips}</td></tr>`).join('')}</tbody></table></div>`:`<p>${t('No visits recorded in this period. Open a public-facing demo page to begin collecting measurements.','No hay visitas registradas en este período. Abra una página de la demo para comenzar a recopilar mediciones.')}</p>`}</article><section class="section grid two">${table(t('Popular pages','Páginas populares'),r.groups.path)}${table(t('Device categories','Categorías de dispositivo'),r.groups.device)}${table(t('Browsers','Navegadores'),r.groups.browser)}${table(t('Operating systems','Sistemas operativos'),r.groups.os)}${table(t('Referring websites','Sitios de origen'),r.groups.referrer)}${table(t('Languages','Idiomas'),r.groups.language)}</section><p class="source">${t('Staff workspace views, known bots and privacy-signal visits are excluded. JavaScript blockers and network failures can undercount. No past traffic is reconstructed. Only 30 UTC days are retained; older data is pruned on collection/report access. Hosting logs are separate.','Se excluyen vistas del espacio del personal, bots conocidos y visitas con señales de privacidad. Los bloqueadores y fallos de red pueden reducir los conteos. No se reconstruye tráfico anterior. Se conservan solo 30 días UTC; los datos anteriores se eliminan al recopilar o consultar. Los registros del alojamiento son independientes.')}</p>`;
 document.querySelector('#analytics-status').textContent=t('Updated. Owner-only aggregate report.','Actualizado. Informe agregado exclusivo del propietario.');document.querySelector('#analytics-export').disabled=false;
 }catch{if(n===serial){document.querySelector('#analytics-status').textContent=t('Analytics is unavailable. Try refreshing.','Estadísticas no disponibles. Intente actualizar.');document.querySelector('#analytics-report').innerHTML=''}}}
 document.querySelector('#analytics-days').onchange=load;document.querySelector('#analytics-refresh').onclick=load;document.querySelector('#analytics-export').onclick=()=>{if(report)download('d11-analytics.json',JSON.stringify(report,null,2))};await load();
}
