export function initAnalytics(spanish){
 if(typeof navigator==='undefined'||typeof crypto==='undefined'||!crypto.randomUUID||/staff|messages/.test(location.pathname))return;
 const t=(en,es)=>spanish?es:en,key='d11-analytics-choice-v1',blocked=navigator.globalPrivacyControl===true||navigator.doNotTrack==='1',id=crypto.randomUUID();let choice=null;
 try{choice=JSON.parse(localStorage.getItem(key));if(!choice||choice.expires<Date.now())choice=null}catch{}
 const send=(path,payload)=>fetch(path,{method:'POST',headers:{'content-type':'application/json','x-d11-request':'1'},body:JSON.stringify(payload),keepalive:true});
 const track=()=>{if(blocked)return;send('/api/analytics/visit',{id,path:location.pathname+location.search,language:spanish?'es':'en',referrer:document.referrer||'',consent:choice?.allow===true,browserId:choice?.allow?choice.id:undefined}).catch(()=>{})};
 const save=value=>{choice=value;try{localStorage.setItem(key,JSON.stringify(value))}catch{}};
 const node=document.createElement('section');node.id='privacy-choices';node.className='privacy-choices card';node.setAttribute('aria-label',t('Privacy choices','Opciones de privacidad'));node.hidden=!!choice||blocked;
 node.innerHTML=`<h2>${t('Help us understand site use','Ayúdenos a entender el uso del sitio')}</h2><p>${t('Basic page counts include page, language, device/browser category and referring website. Optional measurement uses a random browser ID and a daily protected IP code to estimate repeat visits. No advertising or fingerprinting.','Los conteos básicos incluyen página, idioma, categoría de dispositivo/navegador y sitio de origen. La medición opcional usa un ID aleatorio del navegador y un código IP protegido diario para estimar visitas repetidas. Sin publicidad ni huellas digitales.')}</p><p>${t('Optional measurement is for adults 18 and older. It is not required to use the site.','La medición opcional es para adultos de 18 años o más. No es necesaria para usar el sitio.')}</p><div class="buttons"><button class="btn" id="privacy-basic">${t('Basic counts only','Solo conteos básicos')}</button><button class="btn" id="privacy-allow" ${blocked?'disabled':''}>${t('I am 18+ and allow optional measurement','Tengo 18 años o más y permito la medición opcional')}</button><button class="btn" id="privacy-forget">${t('Remove my measurement ID','Eliminar mi ID de medición')}</button><a class="btn" href="privacy.html${spanish?'?lang=es':''}">${t('Privacy details','Detalles de privacidad')}</a></div><p id="privacy-status" role="status">${blocked?t('Your privacy signal disables analytics.','Su señal de privacidad desactiva las estadísticas.'):''}</p>`;
 document.querySelector('#footer').prepend(node);const open=document.createElement('button');open.className='btn compact';open.textContent=t('Privacy choices','Opciones de privacidad');open.onclick=()=>{node.hidden=!node.hidden;if(!node.hidden)node.scrollIntoView({block:'nearest'})};document.querySelector('.footer-bottom').append(open);
 const revoke=async()=>{if(choice?.id){const response=await send('/api/analytics/forget',{browserId:choice.id});if(!response.ok)throw new Error('forget')}save({allow:false,expires:Date.now()+30*86400000})};
 document.querySelector('#privacy-allow').onclick=()=>{if(blocked)return;save({allow:true,id:choice?.allow&&choice.id?choice.id:crypto.randomUUID(),expires:Date.now()+30*86400000});track();node.hidden=true};
 const decline=async()=>{try{await revoke();document.querySelector('#privacy-status').textContent=t('Optional identifiers removed. Basic counts remain.','Identificadores opcionales eliminados. Se conservan conteos básicos.');document.querySelector('#privacy-allow').focus()}catch{document.querySelector('#privacy-status').textContent=t('Could not remove the measurement ID. Please try again.','No se pudo eliminar el ID de medición. Inténtelo de nuevo.')}};
 document.querySelector('#privacy-basic').onclick=async()=>{await decline();if(choice?.allow===false)node.hidden=true};document.querySelector('#privacy-forget').onclick=decline;
 // A privacy signal also removes previously opted-in identifiers when possible.
 if(blocked&&choice?.id)revoke().catch(()=>{});track();
}
