export const resources=[
{id:'enrollment',icon:'school',title:'Enroll in District 11',titleEs:'Inscríbase en el Distrito 11',body:'Start with your school and enrollment application. Have parent identification, proof of your child’s date of birth, immunization records, and proof of residency ready. Bring custody or special education documents when applicable.',bodyEs:'Comience con su escuela y la solicitud de inscripción. Prepare identificación del padre o tutor, comprobante de fecha de nacimiento, vacunas y domicilio. Incluya documentos de custodia o educación especial cuando correspondan.',url:'page.html?id=enrollment',label:'Enrollment information',labelEs:'Información de inscripción',contact:'719-520-2297'},
{id:'meals',icon:'book',title:'Meals & nutrition',titleEs:'Comidas y nutrición',body:'Find breakfast and lunch menus, meal benefit applications, and dietary accommodation forms. Schools served by D11 Food and Nutrition Services participate in Healthy School Meals for All. A benefit application may also help with eligible fees and other services.',bodyEs:'Consulte los menús de desayuno y almuerzo, solicitudes de beneficios y formularios de adaptación alimentaria. Las escuelas atendidas por Nutrición de D11 participan en Healthy School Meals for All. Una solicitud de beneficios puede ayudar con cuotas y otros servicios elegibles.',url:'page.html?id=meals',label:'Menus & meal information',labelEs:'Menús e información de comidas'},
{id:'transportation',icon:'school',title:'Transportation & school finder',titleEs:'Transporte y búsqueda de escuelas',body:'Use the district’s family resource hub to find the school locator and transportation information. Confirm your student’s school and current bus arrangements with the district before the first day.',bodyEs:'Use el centro de recursos familiares del distrito para localizar escuelas y consultar información de transporte. Confirme la escuela y el transporte actual de su estudiante antes del primer día.',url:'page.html?id=transportation',label:'Transportation resources',labelEs:'Recursos de transporte'},
{id:'portal',icon:'user',title:'MyPowerHub & SchoolMessenger',titleEs:'MyPowerHub y SchoolMessenger',body:'MyPowerHub uses your existing PowerSchool parent credentials. Ask your school for account help. SchoolMessenger preferences are managed through the SchoolMessenger inbox in MyPowerHub, separately from MyPowerHub notification settings.',bodyEs:'MyPowerHub usa sus credenciales de padre o tutor de PowerSchool. Pida ayuda a su escuela. Las preferencias de SchoolMessenger se administran en su bandeja dentro de MyPowerHub, por separado de las notificaciones de MyPowerHub.',url:'page.html?id=powerschool',label:'Open MyPowerHub',labelEs:'Abrir MyPowerHub'},
{id:'learning',icon:'book',title:'Learning at home',titleEs:'Aprendizaje en casa',body:'Use Schoology to connect with your student’s classroom learning. For assignments, grades, and access questions, contact the classroom teacher or school office.',bodyEs:'Use Schoology para conectarse con el aprendizaje de su estudiante. Para preguntas sobre tareas, calificaciones y acceso, comuníquese con el docente o la oficina escolar.',url:'page.html?id=schoology',label:'Open Schoology',labelEs:'Abrir Schoology'},
{id:'support',icon:'help',title:'A person who can help',titleEs:'Una persona que puede ayudar',body:'Your school office is the starting point for attendance, schedules, learning support, and family questions. Search the school directory for a direct phone number or contact District 11 at 719-520-2000.',bodyEs:'La oficina de su escuela es el primer punto de contacto para asistencia, horarios, apoyo al aprendizaje y preguntas familiares. Busque el teléfono directo en el directorio o llame al Distrito 11 al 719-520-2000.',url:'schools.html',label:'Find school contacts',labelEs:'Buscar contactos escolares'}];
export const calendarSource='page.html?id=district-calendar';
export const sourceEvents=[
{id:'2026-10-09',title:'Teacher Work Day · no students',titleEs:'Día de trabajo docente · sin estudiantes',body:'District calendar date.',bodyEs:'Fecha del calendario del distrito.',eventAt:'2026-10-09T06:00:00Z',eventEnd:'2026-10-10T06:00:00Z',allDay:true},
{id:'2026-10-16',title:'Parent–teacher conferences · no students',titleEs:'Conferencias familiares · sin estudiantes',body:'Contact your school for conference appointments.',bodyEs:'Comuníquese con su escuela para concertar una cita.',eventAt:'2026-10-16T06:00:00Z',eventEnd:'2026-10-17T06:00:00Z',allDay:true},
{id:'2026-10-19',title:'Fall Break · no school',titleEs:'Vacaciones de otoño · sin clases',body:'October 19–23. Classes resume after the break; confirm school-specific details with your school.',bodyEs:'Del 19 al 23 de octubre. Las clases se reanudan después del receso; confirme los detalles con su escuela.',eventAt:'2026-10-19T06:00:00Z',eventEnd:'2026-10-24T06:00:00Z',allDay:true}
].map(x=>({...x,kind:'event',scope:'district',source:calendarSource}));
