import {shell,t,es,esc,api,route} from './common.js';
shell('search');document.title=t('Search · D11','Buscar · D11');
const params=new URLSearchParams(location.search),main=document.querySelector('#main'),types=[['all','Everything','Todo'],['school','Schools & contacts','Escuelas y contactos'],['resource','Family resources','Recursos familiares'],['page','Pages','Páginas'],['news','News','Noticias'],['event','Events','Eventos'],['alert','Alerts','Avisos']];
main.innerHTML=`<section class="wrap section"><div class="pagehead"><span class="eyebrow">${t('Across District 11','En todo el Distrito 11')}</span><h1>${t('What can we help you find?','¿Qué necesita encontrar?')}</h1><p>${t('Search 58 school sites, contacts, family resources, and published updates in English or Spanish.','Busque en 58 sitios escolares, contactos, recursos familiares y novedades publicadas en inglés o español.')}</p></div><form id="search-form" class="card" action="search.html" method="get">${es?'<input type="hidden" name="lang" value="es">':''}<label for="query">${t('Search words or a phone number','Palabras de búsqueda o teléfono')}</label><input id="query" name="q" type="search" maxlength="120" value="${esc(params.get('q')||'')}" placeholder="${t('Try enrollment, meals, or a school name','Pruebe inscripción, comidas o una escuela')}"><div class="grid two"><div><label for="type">${t('Content type','Tipo de contenido')}</label><select id="type" name="type">${types.map(([id,en,sp])=>`<option value="${id}" ${params.get('type')===id?'selected':''}>${t(en,sp)}</option>`).join('')}</select></div><div><label for="scope">${t('Site','Sitio')}</label><select id="scope" name="scope"><option value="all">${t('All sites','Todos los sitios')}</option><option value="district">${t('District resources','Recursos del distrito')}</option></select></div></div><div class="buttons"><button type="submit" class="btn primary">${t('Search','Buscar')}</button><a class="btn" href="${route('search')}">${t('Clear filters','Quitar filtros')}</a></div></form><p id="search-status" role="status" aria-live="polite"></p><div id="results"></div><div id="pagination" class="buttons" aria-label="${t('Search result pages','Páginas de resultados')}"></div></section>`;
try{const schools=await(await fetch('schools-data.json')).json();document.querySelector('#scope').insertAdjacentHTML('beforeend',schools.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join(''));document.querySelector('#scope').value=params.get('scope')||'all'}catch{}
let serial=0;
async function search(page=1){const request=++serial,query=new URLSearchParams({q:document.querySelector('#query').value,type:document.querySelector('#type').value,scope:document.querySelector('#scope').value,page:String(page)});if(es)query.set('lang','es');const status=document.querySelector('#search-status');status.textContent=t('Searching…','Buscando…');document.querySelector('#results').setAttribute('aria-busy','true');
 try{const result=await api('/api/search?'+query);if(request!==serial)return;query.set('page',String(result.page));if(typeof history!=='undefined')history.replaceState(null,'','search.html?'+query);const toggle=document.querySelector('.language'),alternate=new URLSearchParams(query);if(es)alternate.delete('lang');else alternate.set('lang','es');toggle.href='search.html?'+alternate;status.textContent=`${result.total} ${t('results','resultados')} · ${t('Page','Página')} ${result.page} / ${result.pages}`;
 document.querySelector('#results').innerHTML=result.items.length?result.items.map(r=>`<article class="card search-result"><span class="eyebrow">${esc(t(...types.find(x=>x[0]===r.type).slice(1)))}${r.school?' · '+esc(r.school):''}</span><h2><a href="${esc(r.href)}">${esc(r.title)}</a></h2><p>${esc(r.snippet)}</p></article>`).join(''):`<div class="empty"><h2>${t('No matches yet','Sin resultados')}</h2><p>${t('Try fewer words, a school name, or remove a filter. You can also call District 11 at 719-520-2000.','Pruebe menos palabras, el nombre de una escuela o quite un filtro. También puede llamar al Distrito 11 al 719-520-2000.')}</p></div>`;
 document.querySelector('#pagination').innerHTML=[result.page>1?`<button class="btn" data-page="${result.page-1}">${t('Previous','Anterior')}</button>`:'',result.page<result.pages?`<button class="btn" data-page="${result.page+1}">${t('Next','Siguiente')}</button>`:''].join('');for(const button of document.querySelectorAll('[data-page]'))if(button.tagName==='BUTTON')button.onclick=()=>search(Number(button.dataset.page));
 }catch{if(request===serial){status.textContent=t('Search is temporarily unavailable. Please try again.','La búsqueda no está disponible temporalmente. Inténtelo de nuevo.');document.querySelector('#results').innerHTML='';document.querySelector('#pagination').innerHTML=''}}finally{if(request===serial)document.querySelector('#results').removeAttribute('aria-busy')}
}
document.querySelector('#search-form').onsubmit=e=>{e.preventDefault();search()};await search(Number(params.get('page'))||1);
